name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Reports Directory
        run: mkdir -p reports/html

      - name: PerfAction for JMeter
        uses: QAInsights/PerfAction@v5.6.2
        with:
          test-plan-path: './1petstore.octoperf.har.jmx'
          args: "-e -o ./reports/html -Jhost=api.staging.com -Jusers=10"

      - name: Upload HTML Dashboard Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jmeter-html-report
          path: reports/html/petstore/
        with:
          name: jmeter-loadtesting_results
          path: results1/
