name: JMeter Load Test

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  load-test:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run JMeter Non-GUI Test
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path reports\html

          jmeter -n `
            -t ".\1petstore.octoperf.har.jmx" `
            -l ".\result.jtl" `
            -e `
            -o ".\reports\html" `
            -Jhost="api.staging.com" `
            -Jusers=10

      - name: Upload JMeter Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: reports/html/

      - name: Upload JTL Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: result.jtl

